language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("FactorizationMachines"); Pkg.test("FactorizationMachines"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("FactorizationMachines")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
